### ISSUE TITLE
Failed to initialize any socket

### ISSUE THREAD

**Issue by Mano-Liaoyan** [martelkr/cppsocket#37]
Hi, I am trying to to use this library in my project, bit I can initialize any socket/TCP/UDP client, it shows the following error
![image](https://github.com/martelkr/cppsocket/assets/43143420/c3cd26b0-c432-40a4-9bca-80cacc9edb96)
It seems that the winsock function returned an error, does anybody have idea on how to solve this?

**Comment by martelkr** [comment]
Can you post the code you're using to initialize the socket?

**Comment by martelkr** [comment]
@Mano-Liaoyan my guess is this was due to the expectation of a user supplied compilation flag to identify Windows versus Linux. Without the flag, the Windows required WSAStartup function is never called. The issue #35 changed the user supplied compilation flag to check for system defined flags to know if the system is Windows or Linux. This issue should now be fixed in the v0.0.8 release https://github.com/martelkr/cppsocket/releases/tag/v0.0.8. I will close this issue with that fix. Please let me know if you find any other issues.
